ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    print_diagnostics: true

    # Wheel odometry input
    odom0: /diffbot_base_controller/odom
    odom0_config: 
    
      [ true,  true,  false,   # x, y, z
        false, false, true,    # roll, pitch, yaw
        true,  false, false,   # vx, vy, vz
        false, false, true,    # vroll, vpitch, vyaw
        false, false, false ]  # ax, ay, az

    # Now use the fused IMU data
    imu0: /imu/data
    imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      true,  true,  true,
                      true,  true,  true]
    imu0_remove_gravitational_acceleration: true