controller_manager:
  ros__parameters:
    update_rate: 100

    dfrobot_dc_motor_hardware/DFRobotDCMotorHardware:
      type: "dfrobot_dc_motor_hardware/DFRobotDCMotorHardware"
      i2c_device: "/dev/i2c-1"
      i2c_address: "0x10"  # default 0x10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controllers:
      type: "velocity_controllers/JointGroupVelocityController"
      joints:
        - motor1_joint
        - motor2_joint
